export const routes = {
  signin: "/",
  home: "/home",
  signup: "/signup",
  createGroup: "/groups/new",
  newpet: "/pets/new",
  calendar: "/calendar",
  groups: "/groups",
  pets: "/pets",
  pet: "/pet/:petId",
  group: "/group/:groupId",
  editDetals: "/editDetails",
  petEdit: "/pet/:petId/edit",
  groupEdit: "/group/:groupId/edit",
  petMedicalGuests: "/:petId/medical/guests",
};
