# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: npm i
        run: npm i

      # Runs a single command using the runners shell
      - name: Build code
        run: npm run build

      # Runs a set of commands using the runners shell
      - name: Upload to artifect
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./build

      - name: Trigger backend ci/cd
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          event-type: build-menahem-back
          repository: ${{ github.repository_owner }}/menahem-back
